List foodList = [
  {
    'image': 'images/1.jpg',
    'preptime': '45 mins',
    'title': 'Sweet Noodles',
    'desc': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
    'calories': '350',
    'ingredients': 'ingedient 1, ingredient 2',
    'steps': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enjoy!',
  },
  {
    'image': 'images/2.jpg',
    'preptime': '45 mins',
    'title': 'Tomato soup',
    'desc': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
    'calories': '350',
    'ingredients': 'ingedient 1, ingredient 2',
    'steps': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enjoy!',
  },
  {
    'image': 'images/3.jpg',
    'preptime': '45 mins',
    'title': 'Spaghettino',
    'desc': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
    'calories': '350',
    'ingredients': 'ingedient 1, ingredient 2',
    'steps': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enjoy!',
  },
  {
    'image': 'images/4.jpg',
    'preptime': '45 mins',
    'title': 'Rice with Stew',
    'desc': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
    'calories': '350',
    'ingredients': 'ingedient 1, ingredient 2',
    'steps': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enjoy!',
  },
  {
    'image': 'images/5.jpg',
    'preptime': '45 mins',
    'title': 'Delicious Salad',
    'desc': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
    'calories': '350',
    'ingredients': 'ingedient 1, ingredient 2',
    'steps': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enjoy!',
  },
  {
    'image': 'images/6.jpg',
    'preptime': '45 mins',
    'title': 'Pizza Bambino',
    'desc': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
    'calories': '350',
    'ingredients': 'ingedient 1, ingredient 2',
    'steps': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enjoy!',
  },
];
